packages:
  - workflow
  - model
  - ui
  - .
  - test

catalog:
  '@ag-grid-community/client-side-row-model': ^32.1.0
  '@ag-grid-community/core': ^32.1.0
  '@ag-grid-community/vue3': ^32.1.0
  '@changesets/cli': ^2.27.8
  '@milaboratory/pl-block-tools': ^2.1.5
  '@milaboratory/platforma-uikit': ^1.1.11
  '@milaboratory/sdk-test': ^1.5.5
  '@milaboratory/sdk-ui': ^0.12.22
  '@milaboratory/sdk-vue': ^1.1.4
  '@milaboratory/tengo-sdk': ^1.2.2
  '@milaboratory/tengo-template-builder': ^1.14.2
  '@vitejs/plugin-vue': ^5.1.3
  '@vueuse/core': ^11.0.3
  'prettier': ^3.3.3
  'tsup': ~8.1.2
  'typescript': ^5.5.4
  'vite': ^5.4.3
  'vitest': ^2.0.5
  'vue': ^3.4.38
  'vue-tsc': ^2.1.4
