packages:
  - workflow
  - model
  - ui
  - .
  - test

catalog:
  '@changesets/cli': ^2.27.8
  '@milaboratories/uikit': ^1.2.5
  '@platforma-sdk/block-tools': ^2.3.4
  '@platforma-sdk/model': ^1.2.27
  '@platforma-sdk/tengo-builder': ^1.14.11
  '@platforma-sdk/test': ^1.5.23
  '@platforma-sdk/ui-vue': ^1.3.8
  '@platforma-sdk/workflow-tengo': ^1.2.8
  '@types/lodash': ^4.17.9
  '@types/node': ~20.16.5
  '@vitejs/plugin-vue': ^5.1.4
  '@vueuse/core': ^11.1.0
  'lodash': ^4.17.21
  'prettier': ^3.3.3
  'tsup': ^8.3.0
  'typescript': ^5.6.2
  'vite': ^5.4.8
  'vitest': ^2.1.1
  'vue': ^3.5.10
  'vue-tsc': ^2.1.6
