packages:
  - workflow
  - model
  - ui
  - .
  - test

catalog:
  '@changesets/cli': ^2.27.8
  '@milaboratories/uikit': ^1.2.4
  '@platforma-sdk/block-tools': ^2.1.11
  '@platforma-sdk/model': ^1.2.26
  '@platforma-sdk/tengo-builder': ^1.14.11
  '@platforma-sdk/test': ^1.5.15
  '@platforma-sdk/ui-vue': ^1.3.7
  '@platforma-sdk/workflow-tengo': ^1.2.8
  '@types/lodash': ^4.17.7
  '@types/node': ^20.14.10
  '@vitejs/plugin-vue': ^5.1.4
  '@vueuse/core': ^11.1.0
  'lodash': ^4.17.21
  'prettier': ^3.3.3
  'tsup': ^8.3.0
  'typescript': ^5.6.2
  'vite': ^5.4.6
  'vitest': ^2.1.1
  'vue': ^3.5.6
  'vue-tsc': ^2.1.6
