packages:
  - workflow
  - model
  - ui
  - .
  - test

catalog:
  '@changesets/cli': ^2.27.9
  '@platforma-sdk/block-tools': ^2.3.24
  '@platforma-sdk/model': ^1.8.0
  '@platforma-sdk/tengo-builder': ^1.16.1
  '@platforma-sdk/test': ^1.8.16
  '@platforma-sdk/ui-vue': ^1.8.18
  '@platforma-sdk/workflow-tengo': ^2.1.0

  '@types/lodash': ^4.17.13
  '@types/node': ~20.16.15
  '@vitejs/plugin-vue': ^5.2.0
  '@vueuse/core': ^11.2.0
  'lodash': ^4.17.21
  'prettier': ^3.3.3
  'tsup': ^8.3.5
  'typescript': ^5.6.3
  'vite': ^5.4.11
  'vitest': ^2.1.5
  'vue': ^3.5.13
  'vue-tsc': ^2.1.10
