packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@changesets/cli': ^2.27.11
  '@platforma-sdk/block-tools': ^2.5.3
  '@platforma-sdk/model': ^1.20.27
  '@platforma-sdk/tengo-builder': ^2.1.7
  '@platforma-sdk/test': ^1.20.27
  '@platforma-sdk/ui-vue': ^1.20.27
  '@platforma-sdk/workflow-tengo': ^4.7.1
  '@types/lodash': ^4.17.13
  '@vitejs/plugin-vue': ^5.2.1
  '@vueuse/core': ^12.0.0
  'lodash': ^4.17.21
  'prettier': ^3.4.2
  'tsup': ^8.3.5
  'typescript': ~5.6.3
  'turbo': ^2.3.3
  'vite': ^6.0.4
  'vitest': ^2.1.8
  'vue': ^3.5.13
  'vue-tsc': ^2.1.10
