packages:
  - workflow
  - model
  - ui
  - .
  - test

catalog:
  '@changesets/cli': ^2.27.10
  '@platforma-sdk/block-tools': ^2.3.25
  '@platforma-sdk/model': ^1.10.12
  '@platforma-sdk/tengo-builder': ^1.17.3
  '@platforma-sdk/test': ^1.11.1
  '@platforma-sdk/ui-vue': ^1.11.6
  '@platforma-sdk/workflow-tengo': ^2.2.1
  '@types/lodash': ^4.17.13
  '@vitejs/plugin-vue': ^5.2.1
  '@vueuse/core': ^11.3.0
  'lodash': ^4.17.21
  'prettier': ^3.4.1
  'tsup': ^8.3.5
  'typescript': ~5.6.3
  'vite': ^6.0.0
  'vitest': ^2.1.6
  'vue': ^3.5.13
  'vue-tsc': ^2.1.10
