packages:
  - workflow
  - model
  - ui
  - .
  - test

catalog:
  '@changesets/cli': ^2.27.10
  '@platforma-sdk/block-tools': ^2.4.10
  '@platforma-sdk/model': ^1.18.0
  '@platforma-sdk/tengo-builder': ^1.17.3
  '@platforma-sdk/test': ^1.18.0
  '@platforma-sdk/ui-vue': ^1.18.1
  '@platforma-sdk/workflow-tengo': ^2.7.0
  '@types/lodash': ^4.17.13
  '@vitejs/plugin-vue': ^5.2.1
  '@vueuse/core': ^12.0.0
  'lodash': ^4.17.21
  'prettier': ^3.4.2
  'tsup': ^8.3.5
  'typescript': ~5.6.3
  'vite': ^6.0.3
  'vitest': ^2.1.8
  'vue': ^3.5.13
  'vue-tsc': ^2.1.10
