packages:
  - workflow
  - model
  - ui
  - .
  - test

catalog:
  '@changesets/cli': ^2.27.9
  '@milaboratories/uikit': ^1.2.29
  '@platforma-sdk/block-tools': ^2.3.19
  '@platforma-sdk/model': ^1.7.20
  '@platforma-sdk/tengo-builder': ^1.16.0
  '@platforma-sdk/test': ^1.7.23
  '@platforma-sdk/ui-vue': ^1.7.27
  '@platforma-sdk/workflow-tengo': ^1.7.0
  '@types/lodash': ^4.17.13
  '@types/node': ~20.16.15
  '@vitejs/plugin-vue': ^5.1.4
  '@vueuse/core': ^11.1.0
  'lodash': ^4.17.21
  'prettier': ^3.3.3
  'tsup': ^8.3.5
  'typescript': ^5.6.3
  'vite': ^5.4.10
  'vitest': ^2.1.4
  'vue': ^3.5.12
  'vue-tsc': ^2.1.8
