packages:
  - workflow
  - model
  - ui
  - .
  - test

catalog:
  '@changesets/cli': ^2.27.9
  '@milaboratories/uikit': ^1.2.12
  '@platforma-sdk/block-tools': ^2.3.9
  '@platforma-sdk/model': ^1.2.29
  '@platforma-sdk/tengo-builder': ^1.14.13
  '@platforma-sdk/test': ^1.5.33
  '@platforma-sdk/ui-vue': ^1.3.18
  '@platforma-sdk/workflow-tengo': ^1.2.10
  '@types/lodash': ^4.17.10
  '@types/node': ~20.16.10
  '@vitejs/plugin-vue': ^5.1.4
  '@vueuse/core': ^11.1.0
  'lodash': ^4.17.21
  'prettier': ^3.3.3
  'tsup': ^8.3.0
  'typescript': ^5.6.2
  'vite': ^5.4.8
  'vitest': ^2.1.2
  'vue': ^3.5.11
  'vue-tsc': ^2.1.6
